# Generated by Django 2.0.5 on 2018-05-15 18:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='creation_dt',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 18, 5, 26, 600878, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='number',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workorder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
